Repository Git-For-Geeks/Competitive_Programming, pull requests merged in 2022-10, with the labels that each got.

#1 created stuti.py
  stuti.py
Labels: git-for-geeks, medium

#3 Adding a solution to the Best Time to Buy and Sell Stock problem
  Best Time to Buy and Sell Stock/a.out
  Best Time to Buy and Sell Stock/solution.cpp
Labels: git-for-geeks, easy

#7 Solution for problem - Remove Duplicates From Sorted Array
  Remove Duplicates From Sorted Array/Remove_Duplicates_From_Sorted_Array.cpp
  Remove Duplicates From Sorted Array/Remove_Duplicates_From_Sorted_Array.exe
Labels: git-for-geeks, easy

#9 Added solution for integer to roman
  Integer To Roman/Minal.java
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#17 Added Solution for 2 Problems
  Best Time To Buy And Sell Stock II/buySell2.cpp
  Best Time To Buy And Sell Stock II/buySell2.exe
  Best Time To Buy And Sell Stock II/buySell2.py
  Square Root Using Binary Search/sqrt.cpp
  Square Root Using Binary Search/sqrt.exe
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#24 Adding solution of Simple Number
  Single Number/solution_single_number.c++
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#26 Solved Average_Gift and Power of 2 , Both Issues that were assigned
  Some More Questions/Average_Gift.py
  Some More Questions/Power_of_2.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#31 Added solution for Valid Number
  .idea/workspace.xml
  Valid Number/Main.class
  Valid Number/Nishant.java
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#36 n queens solution added
  N-Queens/nqueens.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#34 Create pygame.py
  pygame/pygame.py
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#46 BellaCiao
  Some More Questions/Bella_Ciao.cpp
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#47 Kartik.cpp
  Helpful Math/Kartik.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#50 Adding solution of Beautiful_Matrix
  Beautiful Matrix/Beautiful_Matrix.c++
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#52 Solved Task for Alexey
  Some More Questions/Task_for_Alexey.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#53 Valid Number
  Valid Number/JanWeeee.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#48 Added Trapping Rain problem solution
  Trapping Rain Water/Trapping_Rain_Water.cpp
  Trapping Rain Water/Trapping_Rain_Water.exe
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#54 Solved RR Stone
  Some More Questions/RRSTONE.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#55 Gaurav_Sudoku_Solver
  Sudoku_Solver/Sudoku_Solver.java
Labels: git-for-geeks, medium, hacktoberfest, hacktoberfest-accepted

#61 Traping_Rain_Water_in_Python
  Trapping Rain Water/TrapRainWater.py
Labels: git-for-geeks, hacktoberfest, hacktoberfest-accepted, hard

#62 solved ChefandBoredGames
  Some More Questions/ChefandBoredGames.py
  Some More Questions/ContainerWithMostWater.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#65 Added Book Allocation Solution
  Book Allocation/bookAllocation.cpp
  Book Allocation/bookAllocation.exe
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#69 Solution of Problem "Paper Cutting"
  Paper Cutting/Paper_Cutting.c++
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#68 Aggressive Cows
  Agressive Cows/solution.cpp
  Agressive Cows/solution.exe
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#70 Added Zig Zag Conversion.py
  Some More Questions/Zig Zag Conversion.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#72 Added Chef Learning Hungarian Algorithm.py
  Some More Questions/Chef Learning Hungarian Algorithm.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#78 Added Sereja and Bottles.py
  Some More Questions/Sereja and Bottles.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#81 Maximize Colours from some more probems
  Some More Questions/Maximize Colours.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#83 Added Multi-Colored Segments.py
  Some More Questions/Multi-Colored Segments.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#86 Added Adding Digits.py
  Some More Questions/Adding Digits.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#87 Average Permutation from some more problems
  Some More Questions/Average Permutation from some more problems.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#92 Ultra-Fast Mathematician
  Some More Questions/Ultra-Fast Mathematician.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#93 Added Average Flex.py
  Some More Questions/Average Flex.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#100 Nearly Lucky Number from some more problems
  Some More Questions/Nearly Lucky Number from some more problems.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#106 Letter_combination from some more problems
  Some More Questions/Letter_Combination.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#109 two sum
  Some More Questions/Two_Sum.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#110 Adding solution of Fit_to_Play
  Some More Questions/Fit_to_Play.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#111 Added DZY Loves Chessboard
  Some More Questions/DZY Loves Chessboard.py
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#112 StringToInteger
  .vscode/settings.json
  Some More Questions/StringToInteger.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#113 Sagar Dave- 3 Sum code.
  .vscode/tasks.json
  3 Sum/3sum.py
  Build Race/chef.c
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#114 ArrivalOfGeneral
  Some More Questions/ArrivalOfGeneral.cpp
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#115 Sagar Dave - Building race
  Build Race/main (3).c
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#120 Sagar Dave- Find the Index of the First Occurrence in a String
  First two Strings/strings.java
Labels: git-for-geeks, easy, hacktoberfest, hacktoberfest-accepted

#124 Sagar Dave - Even Odd
  First two Strings/strings.java
  Odd Even/EvenOdd.ipynb
Labels: git-for-geeks, easy
